try {
    var result = "FewFunctionThrowAnError";
    console.log("Result:", result);
}
catch (error) {
    console.error("An error occurred:", error);
}
;
